name: pdfs
on: [push]
jobs:
  run: macos-latest
  container: docker://dcvorg/cml:latest
  steps:
    - uses: actions/checkout@v2
   - name: Setup R
   uses: r-lib/actions/setup-r@master
   
   -name: Setup dependencies
    run: |
      R -e 'install.packages("tidyverse", "googlesheets4")
    
    -name: run the script
      env: 
        repo_token: ${{secrets.GITHUB_TOKEN }}
    
    run: |
      R -e 'run("testmarkdown.Rmd")'
      cml-publish testmarkdown.Rmd
  
