
name: pdfs
on: [push]
jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-pandoc@v1
    - name: Setup R
      uses: r-lib/actions/setup-r@master
     
      
    - name: Setup dependencies
      run: |
       R -e 'install.packages("tidyverse")'
       R -e 'install.packages("rvest")'
       R -e 'install.packages("utilities")'
       R -e 'install.packages("pdftools")'
       R -e 'install.packages("tidytext")'
       R -e 'install.packages("unpivotr")'
       R -e 'install.packages("foreach")'
       R -e 'install.packages("renv")'
       R -e 'install.packages("rmarkdown")'
    
    - name: run the script
      env: 
        repo_token: ${{secrets.GITHUB_TOKEN }}
      run: |
        Rscript -e 'rmarkdown::render("testmarkdown.Rmd")'
        
    - name: Commit files
      run: |
        git config --local core.autocrlf false
        git config --local aljasriin@gmail.com "${{ github.actor }}@users.noreply.github.com"
        git config --local riinaljas "${{ github.actor }}"
        git add . && git add --renormalize .
        git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
        git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
        NO_PAGER=1 git --no-pager diff HEAD^
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
