
name: pdfs
on: [push]
jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-pandoc@v1
    - name: Setup R
      uses: r-lib/actions/setup-r@master
     
      
    - name: Setup dependencies
      run: |
       R -e 'install.packages("tidyverse")'
       R -e 'install.packages("rvest")'
       R -e 'install.packages("utilities")'
       R -e 'install.packages("pdftools")'
       R -e 'install.packages("tidytext")'
       R -e 'install.packages("unpivotr")'
       R -e 'install.packages("foreach")'
       R -e 'install.packages("renv")'
       R -e 'install.packages("rmarkdown")'
    
    - name: run the script
      env: 
        repo_token: ${{secrets.GITHUB_TOKEN }}
      run: |
        Rscript -e 'rmarkdown::render("testmarkdown.Rmd")'

    - name: checkout
      uses: actions/checkout@v2
    - name: Modify value # Tried to modify the files based on existing testfile.txt
      run: |
        echo 'Add value2' >> testfile.txt
    - name: move to dir # Move the generated files into output folder
      run: |
        mkdir -p output
        yes| cp -rf testfile.txt ./output/
    - name: Commit files # commit the output folder
      run: |
          git config --local user.email "aljasriin@gmail.com"
          git config --local user.name "riinaljas"
          git add ./output
          git commit -m "Add changes"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
